steps:
  # Step 1: Build the Docker image
  - name: "us-central1-docker.pkg.dev/cloud-builders/preview/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/sonu-shopify/nextjs-srls-repo/nextjs-srls:${SHORT_SHA}", "."]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "us-central1-docker.pkg.dev/cloud-builders/preview/docker"
    args: ["push", "us-central1-docker.pkg.dev/sonu-shopify/nextjs-srls-repo/nextjs-srls:${SHORT_SHA}"]

  # Step 3: Deploy the Docker image to Cloud Run
  - name: "us-central1-docker.pkg.dev/cloud-builders/preview/cloud-sdk"
    args: ["gcloud", "run", "deploy", "nextjs-srls",
           "--image", "us-central1-docker.pkg.dev/sonu-shopify/nextjs-srls-repo/nextjs-srls:${SHORT_SHA}",
           "--platform", "managed",
           "--region", "us-central1",
           "--allow-unauthenticated"]

options:
  logging: CLOUD_LOGGING_ONLY